### PR TITLE
Add a changelog to our branch

### PR DESCRIPTION
**Pull request by rafatower**
@Algunenano can you please take a quick look?

### CODE REVIEW

**Comment by rafatower** [comment]
cc'ing @pramsey for awareness.

I hope this is clear and simple enough FTM. I'm merging now to not defer things. I'll take care of any comments & suggestions later on.

**Comment by Algunenano** [comment]
I'd add https://github.com/CartoDB/postgres/pull/10 too and leave a link in the Changelog to the PRs or issues for context.

**Comment by rafatower** [comment]
I indeed added PR links for context: https://github.com/CartoDB/postgres/blob/REL_10_CARTO/CHANGELOG.carto.md#101carto-3

I'm experimenting with that `10.1+carto-3` but it shouldn't be painful at all to release a `10.1+carto-4` with the PR you mentioned (and deploy).

Thanks!

**Comment by Algunenano** [comment]
Looks good

**Pull request merged**
